on:
  workflow_dispatch:
  push:
    tags:
      - '*'

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Publish to Open VSX Registry
        uses: Sakai-UI/Sakai-Theme@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: Sakai-UI/Sakai-Theme@v1
        with:
          pat: ${{ secrets.PAT }}
          registryUrl: https://marketplace.visualstudio.com
